name: Package on Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Set system time
        id: beijing_time
        run: echo "BEIJING_TIME=$(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Set team name
        id: team_name
        run: echo "TEAM_NAME='lemonade-lab'" >> $GITHUB_ENV

      - name: Set warehouse name
        id: warehouse_name
        run: echo "WAREHOUSE_NAME='alemonjs-docs'" >> $GITHUB_ENV

      - name: Delete .npmrc
        run: |
          rm -rf .npmrc

      - name: Install Yarn
        run: npm install yarn@1.12.1 -g

      - name: Yarn install
        run: yarn install --ignore-engines

      - name: Build
        run: yarn build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          rsync -avz --delete --ignore-existing ./build/ ${{ secrets.SSH_SERVER_CONFIG }}

      - name: Push docs to GitHub
        run: |
          cd ./build
          git init
          git config --local user.email "ningmengchongshui@gmail.com"
          git config --local user.name "ningmengchongshui"
          git add -A
          git commit -m "自动打包 - ${{ env.BEIJING_TIME }}"
          git remote add github https://${{ env.TEAM_NAME }}:${{ secrets.GH_TOKEN }}@github.com/${{ env.TEAM_NAME }}/${{ env.WAREHOUSE_NAME }}.git
          git push github HEAD:docs -f
